* Обзор приложений-аналогов
** Monetall
** ???
* Описание требуемой функциональности
** ???
* Описание модели данных
** ???
* Описание используемых библиотек
** Realm
** OpenCV
* Описание алгоритма разспознавания изображений

  Небольшая справка.

  К концу практики у нас должен быть заполнен и подписан лист
  задания к дп. То есть нужно составить содержание разделов и
  календарный план, перечень графических материалов, взять задание
  по экономике. Руководитель по экономике у нас Носенко А.А.,
  подойти к ней можно в среду с 12.00 до 14.00 в 810-5.

  В качестве отчёта о практике скорее всего можно будет предоставить
  1 или 2 раздела.

  Примерное содержание разделов:

  1 раздел - обоснование выбора темы, анализ аналогов, постановка
  задачи.

  2 раздел - выбор инструментов, описание этапов разработки

  3 раздел - внедрение, тестирование и поддержка, руководство
  пользователя

  4 раздел - экономика (для программных продуктов обычно это расчёт
  экономической эффективности).

  Количество разделов можно выбирать по своему усмотрению (но вряд
  ли получится меньше)

  FYI: В разделе, где будет описана разработка интерфейса Вашей

  системы/модуля ДОБАВИТЬ подраздел "ЭРГОНОМИКА"! (по решению
  кафедры)
