APP = hf
OBJDIR = obj
BINDIR = bin
SRCS := $(shell find . -name '*.c')
SRCDIRS := $(shell find . -name '*.c' -exec dirname {} \; | uniq)
OBJS := $(patsubst %.c,$(OBJDIR)/%.o,$(SRCS))
DEPS := $(patsubst %.c,$(OBJDIR)/%.d,$(SRCS))
DEBUG = -g -D _DEBUG_
INCLUDES = -I./include
CFLAGS = -std=c89 -pedantic -Wall -O3 $(INCLUDES) -c
DEPENDS = -MT $@ -MD -MP -MF $(subst .o,.d,$@)
SHELL = /bin/bash

.PHONY: all doc run-tests test clean distclean

all: buildrepo $(APP)

$(APP): $(OBJS)
	$(CC) $^ -o $(addprefix $(BINDIR)/, $@)

$(OBJDIR)/%.o: %.c
	$(CC) $(CFLAGS) $(DEPENDS) $< -o $@

clean:
	$(RM) -r $(OBJDIR)
	$(RM) $(shell find . -name '*~')
	$(RM) $(shell find . -name '.\#*')
    
distclean: clean
	$(RM) $(APP)

buildrepo:
	@$(call make-repo)

define make-repo
for dir in $(SRCDIRS); \
do \
mkdir -p $(OBJDIR)/$$dir; \
done
endef
ifneq "$(MAKECMDGOALS)" "distclean"
ifneq "$(MAKECMDGOALS)" "clean"
-include $(DEPS)
endif
endif

run-tests: all
	$(MAKE) -C tests
doc: 
	doxygen Doxyfile
